<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos\ticker.proto" GrpcServices="Server" />
    <!-- Server: "Server" -->
  </ItemGroup>

</Project>
