// <auto-generated />
using DemoEFMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoEFMVC.Migrations
{
    [DbContext(typeof(KentDBContext))]
    [Migration("20260224052426_KentMigration")]
    partial class KentMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoEFMVC.Models.Emp", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("No");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.HasKey("No");

                    b.ToTable("Emp");
                });

            modelBuilder.Entity("DemoEFMVC.Models.Subject", b =>
                {
                    b.Property<int>("SubjecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjecID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjecID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Title");

                    b.HasKey("SubjecID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("DemoEFMVC.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.HasKey("TrainerID");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("SubjectTrainer", b =>
                {
                    b.Property<int>("SubjectsSubjecID")
                        .HasColumnType("int");

                    b.Property<int>("TrainersTrainerID")
                        .HasColumnType("int");

                    b.HasKey("SubjectsSubjecID", "TrainersTrainerID");

                    b.HasIndex("TrainersTrainerID");

                    b.ToTable("SubjectTrainer");
                });

            modelBuilder.Entity("SubjectTrainer", b =>
                {
                    b.HasOne("DemoEFMVC.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsSubjecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoEFMVC.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainersTrainerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
